name: Init repository

on: create

jobs:
  build-and-deploy:
    name: Init repository
    runs-on: ubuntu-latest
    if: endsWith(github.event.ref, 'dist')

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Remove LICENSE and edit default README
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          rm LICENSE
          cp ./.README.md ./README.md
          git commit -am "chore(init): remove default license and update readme"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
